version: '3.8'

services:
  api:
    container_name: api-staging
    env_file:
      - .env.staging
      
  data-collector:
    container_name: data-collector-staging
    env_file: 
      - .env.staging

  mongo-0:
    container_name: mongo-0-staging
    env_file:
      - .env.staging

  mongo-1:
    container_name: mongo-1-staging
    env_file:
      - .env.staging

  mongo-2:
    container_name: mongo-2-staging
    env_file:
      - .env.staging

  mongoclient:
    container_name: mongoclient-staging
    env_file:
      - .env.staging