version: '3.9'

services:
  api:
    image: devintyler2626/tesalate-api:latest
    container_name: api-prod
    command: [ "bash", "-c", "./wait-for-it.sh mongo-0:27017 -- yarn start"]

  data-collector:
    image: devintyler2626/tesalate-data-collector:latest
    container_name: data-collector-prod
    command: [ "bash", "-c", "./wait-for-it.sh mongo-0:27017 -- yarn start"]

  mongo-0:
    container_name: mongo-0-prod

  mongo-1:
    container_name: mongo-1-prod

  mongo-2:
    container_name: mongo-2-prod

  mongoclient:
    container_name: mongoclient-prod