version: '3.9'

services:
  ui:
    container_name: ui
    image: devintyler2626/tesalate-ui:latest
    restart: always
    depends_on:
      - api
    ports:
      - '${UI_PORT:-80}:80'

  api:
    container_name: api
    image: devintyler2626/tesalate-api:latest
    volumes:
      - $PWD/${BUILD_ENVIRONMENT}/api/logs:/home/node/app/logs
    networks:
      - main-network
    restart: always
    env_file:
      - .env
    depends_on:
      - api-cache
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://api:4400/health || exit 1 
      interval: 10s
      start_period: 30s  
    ports:
      - '${API_PORT}:${API_PORT}'
    command: [ "bash", "-c", "yarn start"]

  api-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    healthcheck:
      test: redis-cli ping
      timeout: 5s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - $PWD/${BUILD_ENVIRONMENT}/redis:/data

networks:
  main-network: