version: '3.8'

services:
  api:
    image: devintyler2626/tesalate-api:staging
    container_name: api-staging

  data-collector:
    container_name: data-collector-staging
    env_file: 
      - .env.staging

  mongo-0:
    container_name: mongo-0-staging


  mongo-1:
    container_name: mongo-1-staging


  mongo-2:
    container_name: mongo-2-staging


  mongoclient:
    container_name: mongoclient-staging
